<h1><ruby>剑<rt>jiàn</rt>胆<rt>dǎn</rt>琴<rt>qín</rt>心<rt>xīn</rt></ruby></h1>
<ul>
  <li>male
  <li>ancient style</li>
  <li>snow</li>
  <li>古筝抱在怀里</li>
  <li>江湖侠客</li>
  <li>fair_skin</li>
  <li>black hair</li>
  <li>long hair</li>
  <li>左手抚摸琴弦</li>
  <li>holding a dagger in his right hand</li>
  <li>white silk cloth strip blindfolded</li>
</ul>
